import { NewsArticle } from "@/lib/types";
import { slugify } from "@/lib/utils";

const now = Date.now();
const minutesAgo = (mins: number) => new Date(now - mins * 60000).toISOString();

export const mockNews: NewsArticle[] = [
  {
    id: "1",
    slug: slugify("Global markets react as AI policy pact is signed by 42 nations"),
    title: "Global markets react as AI policy pact is signed by 42 nations",
    summary:
      "Governments agreed on an accelerated framework for frontier model governance, triggering sharp moves across semiconductors and cloud equities.",
    aiSummary:
      "A major international AI agreement was signed. Markets are moving because investors expect new rules to reshape chip demand and cloud spending quickly.",
    aiKeyPoints: [
      "42 countries adopt shared AI compliance principles",
      "Cloud and chip sectors rise on regulatory clarity",
      "Analysts expect rapid enterprise procurement shifts",
    ],
    timeline: [
      { title: "Draft leaked", detail: "Policy clauses appeared in diplomatic channels.", timestamp: minutesAgo(180) },
      { title: "Emergency summit", detail: "Leaders fast-tracked negotiation terms.", timestamp: minutesAgo(90) },
      { title: "Pact ratified", detail: "Member states issued a joint statement.", timestamp: minutesAgo(22) },
    ],
    content:
      "A coordinated policy package has been approved by member states, designed to create interoperable standards for high-capability AI models and cross-border audit controls.",
    source: "Reuters",
    category: "AI",
    image: "https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&w=1600&q=80",
    publishedAt: minutesAgo(22),
    views: 52144,
    isBreaking: true,
    tags: ["ai-policy", "markets", "global"],
  },
  {
    id: "2",
    slug: slugify("Satellite network restored after global communications outage"),
    title: "Satellite network restored after global communications outage",
    summary: "A tier-1 orbital operator restored service after a cascading telemetry failure affected multiple regions.",
    aiSummary: "A global satellite issue disrupted internet and emergency channels. Engineers fixed the core control fault and services are recovering.",
    aiKeyPoints: ["Outage lasted 47 minutes", "Emergency channels prioritized first", "Root cause linked to firmware rollback process"],
    timeline: [
      { title: "Fault detected", detail: "Ground stations report packet loss.", timestamp: minutesAgo(61) },
      { title: "Failover initiated", detail: "Traffic rerouted to backup clusters.", timestamp: minutesAgo(53) },
      { title: "Recovery complete", detail: "Primary channel health returned to normal.", timestamp: minutesAgo(9) },
    ],
    content: "Network operators confirmed service continuity in all major metros with minor latency variance expected through the evening.",
    source: "Bloomberg",
    category: "World",
    image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1600&q=80",
    publishedAt: minutesAgo(9),
    views: 44211,
    isBreaking: true,
    tags: ["satellite", "infrastructure", "world"],
  },
  {
    id: "3",
    slug: slugify("Quantum startup announces practical error-correction milestone"),
    title: "Quantum startup announces practical error-correction milestone",
    summary: "The company demonstrated sustained logical qubits under real production constraints, analysts call it a critical unlock.",
    aiSummary: "A quantum computing company says it fixed a key reliability issue. This could speed up useful commercial quantum systems.",
    aiKeyPoints: ["Record logical qubit stability", "Partnerships with two enterprise labs", "Commercial pilot expected next year"],
    timeline: [{ title: "Lab test", detail: "Internal benchmark met.", timestamp: minutesAgo(300) }],
    content: "Independent researchers are currently validating the benchmark under externally observed workloads.",
    source: "Tech Desk",
    category: "Science",
    image: "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?auto=format&fit=crop&w=1600&q=80",
    publishedAt: minutesAgo(300),
    views: 18333,
    tags: ["quantum", "science", "innovation"],
  },
  {
    id: "4",
    slug: slugify("Bitcoin volatility spikes as sovereign fund discloses major position"),
    title: "Bitcoin volatility spikes as sovereign fund discloses major position",
    summary: "On-chain signals and derivatives volume jumped following an unexpected treasury filing from a state-backed fund.",
    aiSummary: "A large government-backed fund revealed a big Bitcoin position. Prices became more volatile as traders reacted quickly.",
    aiKeyPoints: ["Derivatives open interest up 18%", "Funding rates turn positive", "Market expects policy commentary"],
    timeline: [{ title: "Filing published", detail: "Disclosure hits public wire.", timestamp: minutesAgo(44) }],
    content: "Macro desks view the move as another institutional legitimacy signal in digital assets.",
    source: "Coinwire",
    category: "Crypto",
    image: "https://images.unsplash.com/photo-1518546305927-5a555bb7020d?auto=format&fit=crop&w=1600&q=80",
    publishedAt: minutesAgo(44),
    views: 39002,
    tags: ["bitcoin", "crypto", "markets"],
  },
  {
    id: "5",
    slug: slugify("Major game engine unveils AI-native world simulation pipeline"),
    title: "Major game engine unveils AI-native world simulation pipeline",
    summary: "Developers can generate dynamic narrative systems and persistent NPC memory with new runtime tooling.",
    aiSummary: "A popular game engine added AI tools for deeper, living game worlds. Studios can now build adaptive stories faster.",
    aiKeyPoints: ["Persistent memory graph for NPC behavior", "Lower production cycle time", "Early studio access now open"],
    timeline: [{ title: "Developer keynote", detail: "Feature stack announced.", timestamp: minutesAgo(210) }],
    content: "Studios report significantly lower scripting overhead when building replayable narrative systems.",
    source: "Gaming Weekly",
    category: "Gaming",
    image: "https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=1600&q=80",
    publishedAt: minutesAgo(210),
    views: 12832,
    tags: ["gaming", "ai", "engines"],
  },
  {
    id: "6",
    slug: slugify("EU regulators outline new transparency rules for foundation models"),
    title: "EU regulators outline new transparency rules for foundation models",
    summary: "Draft technical annexes would require structured disclosure on training data provenance and downstream risk assessments.",
    aiSummary: "Europe is drafting clearer rules so big AI models must explain data sources and risks in a structured way.",
    aiKeyPoints: ["Disclosure templates published for comment", "Mid-cap AI names mixed in late trade", "Compliance costs expected to rise"],
    timeline: [],
    content: "Industry groups requested a phased implementation window citing enterprise migration complexity.",
    source: "Policy Wire",
    category: "Politics",
    image: "https://images.unsplash.com/photo-1529107387015-1f2aae888b1e?auto=format&fit=crop&w=1600&q=80",
    publishedAt: minutesAgo(55),
    views: 22100,
    tags: ["eu", "regulation", "ai"],
  },
  {
    id: "7",
    slug: slugify("Pacific trade corridor announces green shipping corridor pilot"),
    title: "Pacific trade corridor announces green shipping corridor pilot",
    summary: "A coalition of ports will trial low-carbon bunkering and synchronized arrival windows to cut idle emissions.",
    aiSummary: "Major ports will test cleaner fuel and better ship scheduling to reduce pollution from ships waiting offshore.",
    aiKeyPoints: ["12 ports join first phase", "Bunkering standards harmonized", "Idle time targeted down 18%"],
    timeline: [],
    content: "Carriers welcomed predictable berthing windows as the most immediate operational win.",
    source: "Maritime Times",
    category: "World",
    image: "https://images.unsplash.com/photo-1494412574643-ff11b0a5c1b3?auto=format&fit=crop&w=1600&q=80",
    publishedAt: minutesAgo(120),
    views: 9800,
    tags: ["shipping", "climate", "trade"],
  },
  {
    id: "8",
    slug: slugify("Defense ministry confirms next-gen radar rollout across northern border"),
    title: "Defense ministry confirms next-gen radar rollout across northern border",
    summary: "Officials cited improved detection of low-altitude objects after a year of field trials in extreme weather.",
    aiSummary: "New radar systems will be installed along a northern border after successful tests in harsh weather.",
    aiKeyPoints: ["Rollout completes by Q4", "Civil aviation coordination updated", "Budget line item approved"],
    timeline: [],
    content: "Analysts noted interoperability upgrades with allied early-warning networks.",
    source: "Defense Brief",
    category: "War",
    image: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1600&q=80",
    publishedAt: minutesAgo(200),
    views: 31200,
    tags: ["defense", "radar", "security"],
  },
  {
    id: "9",
    slug: slugify("Hollywood guild reaches interim deal on generative media credits"),
    title: "Hollywood guild reaches interim deal on generative media credits",
    summary: "Studios agreed to baseline credit language for hybrid productions while a long-term framework is negotiated.",
    aiSummary: "Studios and creatives agreed on basic rules for giving credit when AI is used in making films.",
    aiKeyPoints: ["Credit committee formed", "Retroactive claims excluded", "Strike risk reduced"],
    timeline: [],
    content: "Streamers pushed for clarity before the autumn commissioning cycle.",
    source: "Culture Desk",
    category: "Culture",
    image: "https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=1600&q=80",
    publishedAt: minutesAgo(340),
    views: 15400,
    tags: ["hollywood", "ai", "culture"],
  },
  {
    id: "10",
    slug: slugify("Chip packaging bottleneck eases as new substrate fabs come online"),
    title: "Chip packaging bottleneck eases as new substrate fabs come online",
    summary: "Lead times for advanced substrates fell for the third straight month according to industry trackers.",
    aiSummary: "Making chips ready for devices got faster because new factories for packaging materials started working.",
    aiKeyPoints: ["Lead times down 11%", "Automotive tier-1 relief", "Pricing still elevated"],
    timeline: [],
    content: "Equipment vendors reported higher utilization across advanced packaging lines.",
    source: "Silicon Wire",
    category: "Technology",
    image: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1600&q=80",
    publishedAt: minutesAgo(88),
    views: 27600,
    tags: ["chips", "supply-chain", "hardware"],
  },
  {
    id: "11",
    slug: slugify("Retail banks pilot voice-biometric recovery flows after fraud surge"),
    title: "Retail banks pilot voice-biometric recovery flows after fraud surge",
    summary: "Pilot branches will test passive voice prints for account recovery with strict fallback to in-person verification.",
    aiSummary: "Banks will try using voice recognition for account recovery after more fraud cases.",
    aiKeyPoints: ["Strict fallback rules", "Privacy review ongoing", "Pilot limited to 3 markets"],
    timeline: [],
    content: "Consumer advocates asked for transparent opt-out paths before national rollout.",
    source: "Finance Today",
    category: "Business",
    image: "https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=1600&q=80",
    publishedAt: minutesAgo(410),
    views: 11200,
    tags: ["banks", "security", "fintech"],
  },
  {
    id: "12",
    slug: slugify("Mars sample-return architects propose lighter ascent vehicle design"),
    title: "Mars sample-return architects propose lighter ascent vehicle design",
    summary: "Engineers say a slimmed ascent stage could reduce mission risk while preserving core science objectives.",
    aiSummary: "Scientists suggest a smaller rocket to lift samples from Mars could make the mission safer and still work.",
    aiKeyPoints: ["Mass margin improved", "Launch window unchanged", "Peer review in April"],
    timeline: [],
    content: "NASA and partner agencies will decide after integrated risk simulations conclude.",
    source: "Science Front",
    category: "Science",
    image: "https://images.unsplash.com/photo-1614728894747-a83421e2b9c9?auto=format&fit=crop&w=1600&q=80",
    publishedAt: minutesAgo(720),
    views: 8900,
    tags: ["mars", "space", "science"],
  },
  {
    id: "13",
    slug: slugify("Major esports league adopts server-side anti-cheat for LAN finals"),
    title: "Major esports league adopts server-side anti-cheat for LAN finals",
    summary: "Organizers will run kernel-level checks only on tournament hardware with independent audit logs.",
    aiSummary: "A big esports league will use stronger cheat detection on official computers only, with audit logs.",
    aiKeyPoints: ["LAN-only scope", "Independent audits", "Player union consulted"],
    timeline: [],
    content: "Teams requested clear appeal windows after controversial disqualifications last season.",
    source: "Esports Daily",
    category: "Gaming",
    image: "https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=1600&q=80",
    publishedAt: minutesAgo(155),
    views: 19800,
    tags: ["esports", "anticheat", "gaming"],
  },
];
