import { NewsArticle } from "@/lib/types";
import { slugify } from "@/lib/utils";

const now = Date.now();
const minutesAgo = (mins: number) => new Date(now - mins * 60000).toISOString();

export const mockNews: NewsArticle[] = [
  {
    id: "1",
    slug: slugify("Global markets react as AI policy pact is signed by 42 nations"),
    title: "Global markets react as AI policy pact is signed by 42 nations",
    summary:
      "Governments agreed on an accelerated framework for frontier model governance, triggering sharp moves across semiconductors and cloud equities.",
    aiSummary:
      "A major international AI agreement was signed. Markets are moving because investors expect new rules to reshape chip demand and cloud spending quickly.",
    aiKeyPoints: [
      "42 countries adopt shared AI compliance principles",
      "Cloud and chip sectors rise on regulatory clarity",
      "Analysts expect rapid enterprise procurement shifts",
    ],
    timeline: [
      { title: "Draft leaked", detail: "Policy clauses appeared in diplomatic channels.", timestamp: minutesAgo(180) },
      { title: "Emergency summit", detail: "Leaders fast-tracked negotiation terms.", timestamp: minutesAgo(90) },
      { title: "Pact ratified", detail: "Member states issued a joint statement.", timestamp: minutesAgo(22) },
    ],
    content:
      "A coordinated policy package has been approved by member states, designed to create interoperable standards for high-capability AI models and cross-border audit controls.",
    source: "Reuters",
    category: "AI",
    image: "https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&w=1600&q=80",
    publishedAt: minutesAgo(22),
    views: 52144,
    isBreaking: true,
    tags: ["ai-policy", "markets", "global"],
  },
  {
    id: "2",
    slug: slugify("Satellite network restored after global communications outage"),
    title: "Satellite network restored after global communications outage",
    summary: "A tier-1 orbital operator restored service after a cascading telemetry failure affected multiple regions.",
    aiSummary: "A global satellite issue disrupted internet and emergency channels. Engineers fixed the core control fault and services are recovering.",
    aiKeyPoints: ["Outage lasted 47 minutes", "Emergency channels prioritized first", "Root cause linked to firmware rollback process"],
    timeline: [
      { title: "Fault detected", detail: "Ground stations report packet loss.", timestamp: minutesAgo(61) },
      { title: "Failover initiated", detail: "Traffic rerouted to backup clusters.", timestamp: minutesAgo(53) },
      { title: "Recovery complete", detail: "Primary channel health returned to normal.", timestamp: minutesAgo(9) },
    ],
    content: "Network operators confirmed service continuity in all major metros with minor latency variance expected through the evening.",
    source: "Bloomberg",
    category: "World",
    image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1600&q=80",
    publishedAt: minutesAgo(9),
    views: 44211,
    isBreaking: true,
    tags: ["satellite", "infrastructure", "world"],
  },
  {
    id: "3",
    slug: slugify("Quantum startup announces practical error-correction milestone"),
    title: "Quantum startup announces practical error-correction milestone",
    summary: "The company demonstrated sustained logical qubits under real production constraints, analysts call it a critical unlock.",
    aiSummary: "A quantum computing company says it fixed a key reliability issue. This could speed up useful commercial quantum systems.",
    aiKeyPoints: ["Record logical qubit stability", "Partnerships with two enterprise labs", "Commercial pilot expected next year"],
    timeline: [{ title: "Lab test", detail: "Internal benchmark met.", timestamp: minutesAgo(300) }],
    content: "Independent researchers are currently validating the benchmark under externally observed workloads.",
    source: "Tech Desk",
    category: "Science",
    image: "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?auto=format&fit=crop&w=1600&q=80",
    publishedAt: minutesAgo(300),
    views: 18333,
    tags: ["quantum", "science", "innovation"],
  },
  {
    id: "4",
    slug: slugify("Bitcoin volatility spikes as sovereign fund discloses major position"),
    title: "Bitcoin volatility spikes as sovereign fund discloses major position",
    summary: "On-chain signals and derivatives volume jumped following an unexpected treasury filing from a state-backed fund.",
    aiSummary: "A large government-backed fund revealed a big Bitcoin position. Prices became more volatile as traders reacted quickly.",
    aiKeyPoints: ["Derivatives open interest up 18%", "Funding rates turn positive", "Market expects policy commentary"],
    timeline: [{ title: "Filing published", detail: "Disclosure hits public wire.", timestamp: minutesAgo(44) }],
    content: "Macro desks view the move as another institutional legitimacy signal in digital assets.",
    source: "Coinwire",
    category: "Crypto",
    image: "https://images.unsplash.com/photo-1518546305927-5a555bb7020d?auto=format&fit=crop&w=1600&q=80",
    publishedAt: minutesAgo(44),
    views: 39002,
    tags: ["bitcoin", "crypto", "markets"],
  },
  {
    id: "5",
    slug: slugify("Major game engine unveils AI-native world simulation pipeline"),
    title: "Major game engine unveils AI-native world simulation pipeline",
    summary: "Developers can generate dynamic narrative systems and persistent NPC memory with new runtime tooling.",
    aiSummary: "A popular game engine added AI tools for deeper, living game worlds. Studios can now build adaptive stories faster.",
    aiKeyPoints: ["Persistent memory graph for NPC behavior", "Lower production cycle time", "Early studio access now open"],
    timeline: [{ title: "Developer keynote", detail: "Feature stack announced.", timestamp: minutesAgo(210) }],
    content: "Studios report significantly lower scripting overhead when building replayable narrative systems.",
    source: "Gaming Weekly",
    category: "Gaming",
    image: "https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=1600&q=80",
    publishedAt: minutesAgo(210),
    views: 12832,
    tags: ["gaming", "ai", "engines"],
  },
];
